// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCznC1NIah0KYO_m2t4m6l4VoqHMsDJSK4',
    appId: '1:469599062216:web:535fc3f3ca10bc65f1bdfd',
    messagingSenderId: '469599062216',
    projectId: 'futhinos-522ad',
    authDomain: 'futhinos-522ad.firebaseapp.com',
    storageBucket: 'futhinos-522ad.appspot.com',
    measurementId: 'G-5WLDCPBYV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBR7Wh9pQMwgFeuJNN4hx9kbMY5wtX9UQ',
    appId: '1:469599062216:android:540e59d79525dc5ef1bdfd',
    messagingSenderId: '469599062216',
    projectId: 'futhinos-522ad',
    storageBucket: 'futhinos-522ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcjK9KBE0J-XRvVsSLhTCihbLHLbpIOWk',
    appId: '1:469599062216:ios:a6a23a7e1b019cb1f1bdfd',
    messagingSenderId: '469599062216',
    projectId: 'futhinos-522ad',
    storageBucket: 'futhinos-522ad.appspot.com',
    iosBundleId: 'com.example.futhinosV2',
  );
}
