/// Flutter icons Brazil
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Brazil
///      fonts:
///       - asset: fonts/Brazil.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Brazil {
  Brazil._();

  static const _kFontFam = 'Brazil';
  static const String? _kFontPkg = null;

  static const IconData globe = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brazil = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
